### PR TITLE
Supports providing an alternate GOPATH using the .gopath file

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by mozowski** [comment]
Hi, how can I change GOPATH with your package in OpenShift?

**Comment by fabianofranz** [comment]
@smarterclayton Made the custom GOPATH additive. Bonus, upgrade to Go 1.4.1. Should we merge this?

**Comment by smarterclayton** [comment]
LGTM.  Can you do a test deploy after I merge?

**Comment by fabianofranz** [comment]
@smarterclayton Will do (just did against fabianofranz/openshift-go-cart too).

**Comment by mozowski** [comment]
Hi guys,
thank you for this commit! Now, after I do ssh to my application directory and do echo $GOPATH I can see additional path there.

**Comment by fabianofranz** [comment]
@mozowski Thanks for the feedback!

**Pull request merged**
